os: linux
language: node_js
node_js:
  - node
  
git:
  depth: false

script:
  - npm install tools/pkgeval_badges
  - node tools/pkgeval_badges/src/cli.js

# deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
