branches:
  only:
    - master
git:
  depth: 1
language: node_js
node_js:
  - node
os: linux

script:
  - cd tools/pkgeval_badges
  - npm install
  - cd ../..
  - node tools/pkgeval_badges/src/cli.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
