name: GitHub pages

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '19'

      - name: Generate badges
        run: |
          npm install ./tools/pkgeval_badges
          node tools/pkgeval_badges/src/cli.js public/pkgeval_badges

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'

      - name: Generate charts
        run: |
          julia --project=tools/pkgeval_charts -e 'using Pkg; Pkg.instantiate()'
          julia --project=tools/pkgeval_charts tools/pkgeval_charts/main.jl public/pkgeval_charts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
