name: PkgEval charts

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'

      - name: Generate
        run: |
          julia --project tools/pkgeval_charts -e 'using Pkg; Pkg.instantiate()'
          julia --project tools/pkgeval_charts tools/pkgeval_charts/main.jl public/pkgeval_charts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
